spring:
  application:
    name: user-center
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moxin-user?serverTimezone=UTC
    username: root
    password: root
  #  session 失效时间
  session:
    timeout: 86400

    #屏蔽org包中的日志输出
    logging:
      level:
        org: off

# 端口
server:
  port: 8080
  servlet:
    context-path: /api


# 配置 mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      # 主键生成策略 自增
      id-type: auto
  configuration:
    # 关闭列名自动驼峰命名规则映射
    map-underscore-to-camel-case: false
    # 配置逻辑删除
    # 全局逻辑删除字段名
    logic-delete-field: deleted
    # 逻辑已删除值( 默认为1 )
    logic-delete-value: 1
    # 逻辑未删除值( 默认值0 )
    logic-not-delete-value: 0
    # 开启 sql 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.moxin.moxincreateuser.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn



# 日志格式
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS}%clr(%-5level) --- [%-15thread]%cyan(%-50logger{50}):%msg%n'